### ISSUE TITLE
First example

### ISSUE THREAD

**Issue by eborghi10** [ecostech/rosproxy#1]
First of all, thanks for releasing this repo. Is very helpful.

I'm having issues using it. I copied the `rosproxy_msgs` folder into `ros_lib` directory, but Arduino is failing to compile an example. Does the `rosproxy_arduino/sketchbook/Imu.ino` example have to be compiled using Arduino IDE? I obtained the following error:

```
 fatal error: rosproxy_msgs/Imu.h: No such file or directory
 #include <rosproxy_msgs/Imu.h>
```

This can be solved adding `#include<ros.h>`, but I think that any modification should be necessary. 

Also when I run `rosrun rosserial_client make_library.py ~/sketchbook/libraries rosproxy_msgs`, I get:

```bash
[rosrun] Couldn't find executable named make_library.py below /opt/ros/kinetic/share/rosserial_client
```

Is this command outdated?

**Comment by attermann** [comment]
Hello Emiliano,

I am glad that you find this repo useful.

Regarding compiling the examples, you are correct about the need to include ros.h.  In my application I use Imu.ino and Odom.ino as modules in a larger project, and the main file for the project contains the “#include <ros.h>”.

The command to build the libraries may very well be outdated.  What version of ROS are you using?  You shouldn’t need to re-build rosproxy_msgs unless you change the message definitions.  If you have changed them and are still. Having trouble re-building them, let me know and I will checkin into it and see if maybe there are some missing steps in that process.

Regards,

Chad.

**Comment by eborghi10** [comment]
Thanks for replying, Chad. I made it work inserting Odom methods inside another project.

I think I'll contribute to your project during the following days or next week once I finished with my AS5048A encoders. This repo is very useful for Arduino!
